name: Prueba Python

on: push

jobs: 
    hola-tarea:
      runs-on: ubuntu-latest
      steps:
        - name: Descargar el codigo
          uses: actions/checkout@v4

        - name: Instalar pytest
          run: pip install pytest

        - name: Ejecutar codigo
          run: pytest test.py 
        
      
      
